<a href="https://colab.research.google.com/github/marlevilla/AULA11/blob/main/Pandas_I_O.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Aula 1 -Leyendo archivos CSV

Importando archivos CSV

In [ ]:
import pandas as pd

In [ ]:
datos = pd.read_csv('superstore_data.csv')

In [ ]:
datos.head()

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835.0,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,1,1961,Graduation,Single,57091.0,0,0,6/15/2014,0,464,...,7,0,37,1,7,3,7,5,1,0
2,10476,1958,Graduation,Married,67267.0,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
3,1386,1967,Graduation,Together,32474.0,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
4,5371,1989,Graduation,Single,21474.0,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0

In [ ]:
datos_punto_coma = pd.read_csv('superstore_data_punto_coma.csv')

In [ ]:
datos_punto_coma.head()

  Id;Year_Birth;Education;Marital_Status;Income;Kidhome;Teenhome;Dt_Customer;Recency;MntWines;MntFruits;MntMeatProducts;MntFishProducts;MntSweetProducts;MntGoldProds;NumDealsPurchases;NumWebPurchases;NumCatalogPurchases;NumStorePurchases;NumWebVisitsMonth;Response;Complain
0  1826;1970;Graduation;Divorced;84835;0;0;6/16/2...
1  1;1961;Graduation;Single;57091;0;0;6/15/2014;0...
2  10476;1958;Graduation;Married;67267;0;1;5/13/2...
3  1386;1967;Graduation;Together;32474;1;1;11/5/2...
4  5371;1989;Graduation;Single;21474;1;0;8/4/2014...

Giovanna es una científica de datos que trabaja en una empresa de comercio electrónico. Ella es responsable de analizar datos de ventas para identificar patrones y tendencias que puedan ayudar a la empresa a tomar decisiones informadas.

Recientemente, le asignaron una nueva tarea: analizar un archivo CSV que contiene información sobre las ventas de la empresa durante un período determinado. Para ello, Giovanna intentó leer un archivo CSV en Google Colab, usando la biblioteca Pandas con el siguiente comando:

import pandas as pd
df = pd.read_csv('datos.csv')

En español, el mensaje significa UnicodeDecodeError: el códec 'utf-8' no puede decodificar el byte 0xff en la posición 0: byte de inicio inválido

Pero ¿qué significa eso? ¿Qué es esto de UTF-8?

El error de encoding ocurre cuando la biblioteca Pandas no puede interpretar correctamente los caracteres en un archivo CSV. Esto puede suceder cuando contiene caracteres especiales que la biblioteca Pandas no reconoce o cuando se guardó en un formato de codificación diferente al esperado.

Para resolver este error, es necesario identificar la codificación correcta del archivo CSV y especificarla al cargar el archivo con la biblioteca Pandas. Esta codificación predeterminada es UTF-8, pero en algunos casos, es posible que el archivo se haya guardado con una codificación diferente, como ISO-8859-1.

UTF-8 es una codificación de caracteres universal que se utiliza para representar caracteres de diferentes idiomas de una manera compatible con Internet y los sistemas de computadora en general. Las siglas UTF significan Unicode Transformation Format (Formato de Transformación Unicode) y el número 8 indica que esta codificación asocia una secuencia de 1 a 4 bytes (8 a 32 bits) a cada carácter.

La codificación UTF-8 se usa ampliamente en Internet y en sistemas informáticos de todo el mundo, ya que permite representar caracteres de diferentes idiomas en un solo conjunto de caracteres. Además, esta codificación puede preservar la compatibilidad con codificaciones más antiguas como ASCII, lo que la convierte en una opción popular para crear y compartir archivos de texto.

Quizás estés pensando ahora mismo: ¿cómo podría Giovanna descubrir cuál es la codificación del archivo que está intentando leer?

Hay algunas formas de resolver esto, sin embargo, tendremos la oportunidad de experimentar una forma práctica de hacerlo en el propio Google Colab. ¿Vamos allá?

Podemos usar una biblioteca llamada chardet para detectar el encoding de un archivo CSV. Para usar esta biblioteca en Google Colab, simplemente importela:

import chardet

Luego escribimos el siguiente bloque de código:

with open('datos.csv', 'rb') as file:
    print(chardet.detect(file.read()))

Observe que la primera línea de este código abre el archivo CSV en modo de lectura binaria rb y asigna el objeto del archivo devuelto a una variable llamada file.

En la segunda línea de código, el contenido del archivo CSV se lee usando el método read() y el resultado se pasa a la función chardet.detect(), que devuelve un diccionario que contiene información sobre la codificación más probable del archivo. El resultado se imprime con la función print() que muestra la codificación y la confianza asociada con esa codificación.

Al ejecutar el código Giovanna obtuvo el siguiente resultado:

{'encoding': 'UTF-16', 'confidence': 1.0, 'language': ''}

Ahora ella sabe que es probable que el archivo CSV esté codificado con UTF-16 con una confianza de 1.0. Para especificar la codificación correcta al cargar el archivo CSV con la biblioteca Pandas, puede utilizar un parámetro llamado encoding:

df = pd.read_csv('datos.csv', encoding='UTF-16')

De esta manera, la biblioteca Pandas cargará el archivo CSV usando la codificación UTF-16, lo que resolverá el error de codificación. Entonces, si alguna vez intentas leer un archivo y obtienes el mismo error, ¡recuerda este consejo!

Si deseas profundizar más en el tema, aquí te dejamos algunos enlaces a materiales que fueron utilizados como referencia:

Instituto de Matemáticas y Estadística - IME/USP: Unicode y UTF-8
IBM: ¿Qué es Unicode?
Kaggle: codificaciones de caracteres

In [ ]:
datos_punto_coma = pd.read_csv('superstore_data_punto_coma.csv', sep=';')

In [ ]:
datos_punto_coma.head()

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835.0,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,1,1961,Graduation,Single,57091.0,0,0,6/15/2014,0,464,...,7,0,37,1,7,3,7,5,1,0
2,10476,1958,Graduation,Married,67267.0,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
3,1386,1967,Graduation,Together,32474.0,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
4,5371,1989,Graduation,Single,21474.0,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0

In [ ]:
datos_primeras_lineas = pd.read_csv('superstore_data.csv', nrows = 5)

In [ ]:
datos_primeras_lineas

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,1,1961,Graduation,Single,57091,0,0,6/15/2014,0,464,...,7,0,37,1,7,3,7,5,1,0
2,10476,1958,Graduation,Married,67267,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
3,1386,1967,Graduation,Together,32474,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
4,5371,1989,Graduation,Single,21474,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0

In [ ]:
datos_seleccion = pd.read_csv('superstore_data.csv', usecols = ['Id', 'Year_Birth', 'Income'])
datos_seleccion

         Id  Year_Birth   Income
0      1826        1970  84835.0
1         1        1961  57091.0
2     10476        1958  67267.0
3      1386        1967  32474.0
4      5371        1989  21474.0
...     ...         ...      ...
2235  10142        1976  66476.0
2236   5263        1977  31056.0
2237     22        1976  46310.0
2238    528        1978  65819.0
2239   4070        1969  94871.0

[2240 rows x 3 columns]

In [ ]:
datos_seleccion = pd.read_csv('superstore_data.csv', usecols = [0, 1, 4])
datos_seleccion

         Id  Year_Birth   Income
0      1826        1970  84835.0
1         1        1961  57091.0
2     10476        1958  67267.0
3      1386        1967  32474.0
4      5371        1989  21474.0
...     ...         ...      ...
2235  10142        1976  66476.0
2236   5263        1977  31056.0
2237     22        1976  46310.0
2238    528        1978  65819.0
2239   4070        1969  94871.0

[2240 rows x 3 columns]

Juliana está trabajando en un proyecto de análisis de datos de ventas para una tienda minorista. Ella recibió un conjunto de datos en formato CSV con los valores separados por punto y coma y necesita importarlo a un DataFrame de la biblioteca Pandas para iniciar el análisis.

¿Cuál es la forma correcta de leer este archivo CSV usando la biblioteca Pandas?

pd.read_csv(‘datos_ventas.csv’, sep=‘;’)

Al leer un archivo CSV con la biblioteca Pandas, es importante especificar el separador de campo correcto usando el parámetro sep. La opción predeterminada es una coma (','), por lo que debemos agregar el separador ;

### Escribiendo archivos CSV

In [ ]:
datos_seleccion.to_csv('clientes_mercado.csv')

In [ ]:
clientes_mercado = pd.read_csv('clientes_mercado.csv')
clientes_mercado

      Unnamed: 0     Id  Year_Birth   Income
0              0   1826        1970  84835.0
1              1      1        1961  57091.0
2              2  10476        1958  67267.0
3              3   1386        1967  32474.0
4              4   5371        1989  21474.0
...          ...    ...         ...      ...
2235        2235  10142        1976  66476.0
2236        2236   5263        1977  31056.0
2237        2237     22        1976  46310.0
2238        2238    528        1978  65819.0
2239        2239   4070        1969  94871.0

[2240 rows x 4 columns]

In [ ]:
datos_seleccion.to_csv('datos_mercado.csv', index = False)

In [ ]:
datos_mercado = pd.read_csv('datos_mercado.csv')
datos_mercado

         Id  Year_Birth   Income
0      1826        1970  84835.0
1         1        1961  57091.0
2     10476        1958  67267.0
3      1386        1967  32474.0
4      5371        1989  21474.0
...     ...         ...      ...
2235  10142        1976  66476.0
2236   5263        1977  31056.0
2237     22        1976  46310.0
2238    528        1978  65819.0
2239   4070        1969  94871.0

[2240 rows x 3 columns]

La biblioteca Pandas es una de las herramientas más poderosas disponibles para análisis de datos en Python. Ofrece una amplia variedad de funciones que hacen que el proceso de manipulación y análisis de datos sea mucho más fácil y eficiente.

Para aprovechar al máximo todas las funciones de la biblioteca, es esencial explorar su documentación, que es extensa y está bien organizada, y a la que se puede acceder fácilmente en línea. Consulta las indicaciones:

Función read_csv
Función to_csv
Explorar la documentación de la biblioteca es importante por varias razones. Puede ayudarle a comprender cómo las funciones y métodos de la biblioteca funcionan y cómo se pueden utilizar para analizar y manipular datos.

Además, la documentación proporciona detalles sobre los parámetros de cada función y ejemplos de cómo se pueden utilizar en la práctica. Entonces, intenta profundizar tus estudios sobre los parámetros de cada función read_csv y to_csv y aprende más sobre cada uno de ellos.

### 09
Desafío: leyendo datos con múltiples parámetros

Es hora de que pongas a prueba los conocimientos desarrollados durante la clase. Disponemos de un archivo en formato CSV, el cual se obtuvo de la página Información de Salud (TABNET) - DATASUS. Este archivo contiene los gastos hospitalarios públicos de cada una de las Unidades de la Federación Brasileña desde enero de 2008 hasta marzo de 2021.

Su desafío aquí será leer este archivo usando la función read_csv de la biblioteca Pandas. Se deben agregar algunos parámetros para que la lectura se realice correctamente. Entonces, aquí hay algunos consejos:

Asegúrese de que el archivo CSV esté separado por una coma o punto y coma.
La codificación del archivo es ISO-8859-1.
Las primeras tres líneas del archivo se pueden ignorar, ya que el encabezado sólo comienza en la cuarta línea.
Las últimas 9 líneas también se pueden ignorar, ya que son sólo información sobre dónde se tomaron los datos.
Para eliminar las últimas líneas es necesario agregar el parámetro engine='python'.
¿Comenzamos?

Para leer el archivo podemos comenzar almacenando la dirección en una variable llamada url:

url = 'datos_sus.csv'
Copia el código
Luego podemos leer la url con la función read_csv y agregar los parámetros:

encoding='ISO-8859-1': tipo de codificación de caracteres del archivo. En este caso, es la codificación ISO-8859-1 la que es común en los archivos en idioma portugués.
sep=';': separador de los valores del archivo. En este caso, es el punto y coma (;).
skiprows=3: indica que las primeras tres líneas del archivo deben ignorarse ya que no contienen datos relevantes.
skipfooter=9: Indica que las últimas nueve líneas del archivo deben ignorarse ya que no contienen datos relevantes.
engine='python': el motor utilizado para leer el archivo es Python. Esto es necesario cuando se utiliza el parámetro skipfooter, ya que el motor predeterminado no admite esta opción.
datos = pd.read_csv(url, encoding='ISO-8859-1', sep=';', skiprows=3, skipfooter = 9, engine='python')
Copia el código
¡De esta manera los datos se cargarán exitosamente!

###Transcripción

Muy bien, sean bienvenidos al capítulo número 2, en el que trabajaremos otro caso de uso diferente, en el cual aprenderemos a importar y escribir en diferentes archivos de bases de datos. En la oportunidad anterior, recordarán que entregamos a nuestro supervisor el análisis que realizamos con esta base de datos en formato CSV. Aprendimos a importar, leer y exportar los datos y mostrar a nuestro supervisor el resultado. Le gustó tanto que nos dijo: "Alejandro, buen trabajo, te vamos a dar un aumento". Yo le digo que un aumento de sueldo, no, un aumento de trabajo. Es decir, nos va a dejar otro proyecto más para trabajar.

En esta oportunidad, vamos a tener que analizar una base de datos de emisiones de dióxido de carbono por países, emisiones de CO2, para saber qué países están realizando una política de sostenibilidad ambiental que están en la moda, en la onda verde. Y para eso, tenemos que trabajar con una base de datos de países. Esta base de datos está en un formato distinto, ya no está en CSV, sino en un formato Excel. Así que vamos a aprender a leer los datos de esta base de datos de Excel para poder importar y trabajar con ellos.

¿Qué es un Excel? Excel es un archivo de Excel. Excel no es un CSV, obviamente. Tiene más características. Para esto, vamos a mostrar un Excel. Podemos venir aquí a un navegador de Google, por ejemplo, y colocar Google Sheets. Sí, tenemos Excel en formato online también. Podemos hacer clic aquí en Google Sheets, iniciar sesión. Si no tenemos el usuario de Gmail registrado, nos registramos y ya nos va a aparecer aquí una hoja de cálculo en blanco, un libro de Excel en blanco, donde podemos tener rápidamente filas y columnas, como si lo hubiésemos abierto del ordenador. Esta es una hoja de cálculo, un libro de Excel en línea, entonces está en Internet.

Aquí también podemos ver las mismas características que si lo abriésemos con el Office, por ejemplo, en el ordenador. Tenemos filas del 1 hasta... A ver, ¿cuál es el final? Del 1 al 1,000. Puedo agregar más filas, si deseo. Y también tengo columnas de la A hasta la Z. Ahora, según la posición donde me coloque dentro del Excel, estoy en una posición de filas y columnas. Por ejemplo, si selecciono esta de aquí, en el canto superior izquierdo ya me indica en qué celda me encuentro. En este caso, me encuentro en la celda E8. Y así puedo ir cambiando de celda y se va a cambiar la posición aquí en esta parte.

Lo que tenemos aquí son las hojas, las hojas de Excel. Un libro de Excel puede tener más de una hoja. Por ejemplo, si hago clic aquí en el Más, voy a añadir más hojas. Hoja 1, hoja 2, hoja 3. Y en cada una de las hojas puedo tener una información diferente. Aquí puedo guardar nombres, aquí puedo guardar productos, aquí puedo guardar ofertas, etc. Y aquí es el nombre del Excel. Actualmente está como hoja de cálculo sin título, pero puedo escribirle mi primer libro de Excel. Si quisiera que se llame así, por ejemplo. Ya está. Y esto está guardado ya en tu cuenta de Google automáticamente. No necesito estar guardándolo, ya se guarda online.

Esto es un Excel. Para los que no conocían, hicimos un refresco rápido. Y ahora sí, vamos a conocer la base en Excel que tenemos para nuestro trabajo. Podemos venir a la lección número 2. Lo pueden encontrar en el repositorio del proyecto. Entrar al folder Data y aquí van a encontrar emisiones CO2.xlsx. Ese .xlsx es la extensión de un archivo Excel. Es decir, que cada vez que vean esta extensión .xlsx, están viendo un archivo de Excel, que es exactamente esto que vimos aquí. Si hago doble clic, me va a abrir el Excel que tengo en el ordenador o también lo puedo importar a este Google Sheets Online.

Pero nosotros no lo vamos a trabajar por aquí, ¿verdad? Queremos trabajarlos en Python. Entonces, para eso tenemos que importarlo a nuestro colab. Vamos a volver aquí a nuestro colab. Ya me adelanté la lección número 2 leyendo archivos de Excel y nuevamente vamos a importar ese archivo aquí a nuestros documentos. Hacemos clic en esta flechita, lo buscamos. ¿Dónde está? Documentos. A ver, yo lo guardé por aquí. Déjame buscarlo rápido en la lección número 2, Data, Emisiones, CO2. Seleccionamos y hacemos clic en Open. Nuevamente, esta advertencia que nos dice si cierras el ordenador, no lo encuentras más, ¿ok? Ok. Entendemos eso. No se preocupen. Lo vamos a abrir y lo vamos a usar rápido. No necesitamos tenerlo aquí para siempre.

Esto demora un poco más en cargar. Ven este semicírculo azul. Es el avance de la importación del archivo porque es un archivo un poco más pesado que el que trabajamos en el primer capítulo, que es el CSV. Entonces, esto solamente estará completo o estará disponible una vez que el círculo se complete totalmente de azul. Entonces, nos va a demorar un poco y nada más. Una vez que termine el círculo de llenar, aquí vamos a poder utilizar ya el archivo Excel.

Y ahora, ¿cómo podemos importar el archivo Excel en nuestro colab? Nuevamente, vamos a importar pandas como pd. Vamos a ejecutar esto de aquí. Ya está. Porque necesitamos utilizar métodos de pandas para poder importar archivos, igual que lo hicimos en el capítulo anterior. Ya importó el Excel. Ya está aquí, ya está disponible. Voy a copiar el nombre, que lo voy a necesitar de la misma forma que lo hicimos en el capítulo anterior. Voy a cerrar aquí para tener más espacio. Una nueva línea de código. Y ahora sí, vamos a importar el archivo.

Antes de importar el archivo, voy a guardar el nombre del archivo para no estar escribiendo y copiando y pegando todo el tiempo. En esta variable, voy a crear una variable archivo y voy a colocar entre las comillas simples el nombre del archivo. De esta manera, no tengo que estar escribiendo a toda hora emisiones CO2, emisiones CO2, emisiones CO2, sino que ya referencio a la variable archivo. Esto es para optimizar el código. Adiciono una línea más y ahora sí, vamos a leer.

¿Recuerdan cómo se leía archivos CSV? El método era read_csv. ¿Correcto? Correcto. Para leer Excel no es muy diferente. Solamente cambiamos el CSV por Excel. Y ya está. Muy fácil, ¿verdad? Cada vez que tengamos que leer una base de datos con pandas, simplemente el método es read_ y alguna cosa. CSV, Excel, JSON, ya vamos a ver para los demás formatos de archivos.

Y aquí tenemos que colocar, ¿qué cosa? El nombre del archivo, ¿verdad? Como ya lo tengo automatizado aquí, ya lo tengo guardado aquí, solamente lo voy a colocar archivo dentro de los paréntesis. Esto lo vamos a guardar en una nueva variable, digamos, datos_co2. Voy a asignar el resultado aquí. Se me fue un espacio. Lo voy a ejecutar y luego lo voy a mostrar en pantalla. Aquí ya estoy importando el archivo Excel, todo su contenido dentro de una variable datos_co2. datos_co2 automáticamente se convierte en un dataframe porque este método devuelve un dataframe.

Entonces, como esto es un dataframe, puedo ejecutar el método de un dataframe llamado head para mostrar los cinco primeros, sí, las cinco primeras líneas de un archivo. Ahora, me está mostrando los cinco primeros registros del archivo emisiones CO2. ¿Qué contiene? Los nombres de los países, un código alfanumérico que indica el nombre del país en un formato alfanumérico, en un código, el año del cual se obtuvo este resultado y el total de emisiones, aquí en esta columna, y el detalle por tipo de emisión. Carbónico, aceite, gas, cemento, quema, otros per cápita.

Entonces, tenemos mucha información en estas primeras cinco líneas. No tengo datos para mostrar, pero tal vez en las siguientes, sí. Y una de las características que habíamos hablado de un Excel, vuelvo aquí al Google Sheets, es que tiene hojas, ¿verdad? Entonces, aquí yo no sé exactamente qué hoja estoy viendo. No sé si estoy viendo la primera, la segunda, la tercera, no lo sé. Para esto, voy a añadir una nueva línea de código. Puedo examinar con el método pd, a ver, pd pandas ExcelFile, que quiero abrir este archivo de Excel, que se llama, ¿cómo se llama? Se llama archivo, ¿verdad? Quiero abrir, quiero examinar ese archivo y voy a llamar al método sheet_names, ¿que sería qué cosa? Nombres de las hojas. Quiero que me devuelva una lista con todas las hojas que contiene este Excel, para poder saber con cuál de ellas voy a trabajar.

Ejecuto esto de aquí y en pantalla me va a aparecer que sí, ese libro de Excel, ese libro de Excel, ese Excel tiene tres hojas. La primera se llama emisiones CO2, emisiones per cápita y fuentes. En realidad, creo que estoy viendo la primera, emisiones CO2. Pero si quisiera ver la segunda hoja, esta de aquí, si quisiera ver la tercera hoja, ¿cómo podría hacerlo? Pues para esto, vamos a explorar los parámetros del método ReadExcel, de la misma forma que lo hicimos en el primer capítulo, vamos a explorar qué otros parámetros tiene para poder abrir exactamente la hoja que quiero.

Muy bien, vamos a ver esto ya a partir del próximo video. Los espero.

### Aula 2 - Leyendo archivos Excel

### Importando archivos Excel

In [ ]:
import pandas as pd

In [ ]:
archivo = 'emisiones_CO2.xlsx'

In [ ]:
pd.read_excel(archivo)

,País,ISO 3166-1 alpha-3,Año,Total,Carbón,Aceite,Gas,Cemento,Quema,Otros,Per Capita
0,Afganistán,AFG,1750,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afganistán,AFG,1751,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afganistán,AFG,1752,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afganistán,AFG,1753,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afganistán,AFG,1754,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
63099,Global,WLD,2017,3.609674e+10,1.450697e+10,1.224263e+10,7.144928e+09,1.507923e+09,391992176.0,302294047.0,4749682.0
63100,Global,WLD,2018,3.682651e+10,1.474683e+10,1.226602e+10,7.529847e+09,1.569218e+09,412115746.0,302478706.0,4792753.0
63101,Global,WLD,2019,3.708256e+10,1.472598e+10,1.234565e+10,7.647528e+09,1.617507e+09,439253991.0,306638573.0,4775633.0
63102,Global,WLD,2020,3.526409e+10,1.417456e+10,1.119181e+10,7.556290e+09,1.637538e+09,407583673.0,296301685.0,4497423.0
63103,Global,WLD,2021,3.712385e+10,1.497960e+10,1.183716e+10,7.921829e+09,1.672592e+09,416525563.0,296145746.0,4693699.0

In [ ]:
datos_co2 = pd.read_excel(archivo)

In [ ]:
datos_co2.head()

,País,ISO 3166-1 alpha-3,Año,Total,Carbón,Aceite,Gas,Cemento,Quema,Otros,Per Capita
0,Afganistán,AFG,1750,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afganistán,AFG,1751,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afganistán,AFG,1752,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afganistán,AFG,1753,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afganistán,AFG,1754,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
pd.ExcelFile(archivo).sheet_names

['emisiones_C02', 'emisiones_percapita', 'fuentes']

Introducción a Excel:
Excel es diferente de CSV y ofrece más características, como hojas múltiples en un solo archivo.
Se muestra una introducción rápida a Google Sheets como ejemplo de Excel en línea.
Cada hoja de Excel se compone de filas y columnas, y puedes referenciar celdas específicas (ej., E8).
Un libro de Excel puede contener múltiples hojas, cada una con información diferente.
Importando archivos Excel en Colab:
Se descarga un archivo Excel (emisiones CO2.xlsx) desde el repositorio del proyecto.
Se explica cómo importar este archivo a Google Colab.
Se advierte que los archivos importados de esta manera son temporales y se eliminan al cerrar la sesión.
Lectura de archivos Excel con Pandas:
Se importa la librería pandas como pd.
Se crea una variable archivo para guardar el nombre del archivo Excel y optimizar el código.
Se utiliza el método read_excel de Pandas para leer el archivo Excel y guardarlo en un dataframe llamado datos_co2.
Se utiliza el método head para mostrar las primeras cinco líneas del dataframe y examinar su contenido.
Exploración de hojas en Excel:
Se utiliza el método pd.ExcelFile junto con sheet_names para listar todas las hojas en el archivo Excel.
Se identifica que el archivo tiene tres hojas: emisiones CO2, emisiones per cápita y fuentes.
Se plantea la necesidad de explorar los parámetros del método read_excel para seleccionar una hoja específica al importar el archivo.

In [ ]:
percapita = pd.read_excel(archivo, sheet_name='emisiones_percapita')

In [ ]:
  percapita.head()

,País,ISO 3166-1 alpha-3,Año,Total,Carbón,Aceite,Gas,Cemento,Quema,Otros
0,Afganistán,AFG,1750,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afganistán,AFG,1751,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afganistán,AFG,1752,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afganistán,AFG,1753,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afganistán,AFG,1754,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
percapita.sample(5)

,País,ISO 3166-1 alpha-3,Año,Total,Carbón,Aceite,Gas,Cemento,Quema,Otros
25313,India,IND,1767,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24494,Hong Kong,HKG,1764,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47879,Santa Elena,SHN,1757,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22034,Groenlandia,GRL,1752,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26742,Israel,ISR,1836,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
fuentes = pd.read_excel(archivo, sheet_name='fuentes')

In [ ]:
fuentes.tail()

,País,ISO 3166-1 alpha-3,Año,Total,Carbón,Aceite,Gas,Cemento,Quema,Otros,Per Capita
63099,Global,WLD,2017,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."
63100,Global,WLD,2018,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."
63101,Global,WLD,2019,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."
63102,Global,WLD,2020,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."
63103,Global,WLD,2021,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."

In [ ]:
intervalo = pd.read_excel(archivo, sheet_name='emisiones_C02', usecols='A:D')

In [ ]:
intervalo

             País ISO 3166-1 alpha-3   Año         Total
0      Afganistán                AFG  1750  0.000000e+00
1      Afganistán                AFG  1751  0.000000e+00
2      Afganistán                AFG  1752  0.000000e+00
3      Afganistán                AFG  1753  0.000000e+00
4      Afganistán                AFG  1754  0.000000e+00
...           ...                ...   ...           ...
63099      Global                WLD  2017  3.609674e+10
63100      Global                WLD  2018  3.682651e+10
63101      Global                WLD  2019  3.708256e+10
63102      Global                WLD  2020  3.526409e+10
63103      Global                WLD  2021  3.712385e+10

[63104 rows x 4 columns]

In [ ]:
intervalo_2 = pd.read_excel(archivo, sheet_name='emisiones_C02', usecols='A: D', nrows =10)

In [ ]:
intervalo_2

         País ISO 3166-1 alpha-3   Año  Total
0  Afganistán                AFG  1750      0
1  Afganistán                AFG  1751      0
2  Afganistán                AFG  1752      0
3  Afganistán                AFG  1753      0
4  Afganistán                AFG  1754      0
5  Afganistán                AFG  1755      0
6  Afganistán                AFG  1756      0
7  Afganistán                AFG  1757      0
8  Afganistán                AFG  1758      0
9  Afganistán                AFG  1759      0

df = pd.read_excel('datos.xlsx', sheet_name='pagos', usecols='F:L', nrows=50)

El parámetro sheet_name se utiliza para especificar la página de la hoja de cálculo que Théo quiere leer. En este caso, es la página "pagos". El parámetro usecols se utiliza para especificar las columnas que se leerán, que son las columnas de la F a la L. Además, el parámetro nrows se agregó para especificar el número de líneas que Théo quiere leer, que es 50.

In [ ]:
intervalo.to_excel('co2_percapita.xlsx', index = False)

In [ ]:
pd.read_excel('co2_percapita.xlsx')

             País ISO 3166-1 alpha-3   Año         Total
0      Afganistán                AFG  1750  0.000000e+00
1      Afganistán                AFG  1751  0.000000e+00
2      Afganistán                AFG  1752  0.000000e+00
3      Afganistán                AFG  1753  0.000000e+00
4      Afganistán                AFG  1754  0.000000e+00
...           ...                ...   ...           ...
63099      Global                WLD  2017  3.609674e+10
63100      Global                WLD  2018  3.682651e+10
63101      Global                WLD  2019  3.708256e+10
63102      Global                WLD  2020  3.526409e+10
63103      Global                WLD  2021  3.712385e+10

[63104 rows x 4 columns]

Google Sheets es una herramienta de hojas de cálculo online basada en nube que le permite crear, editar y colaborar en hojas de cálculo de manera fácil y conveniente. Es una de las aplicaciones de Google Workspace que ofrece una alternativa a Microsoft Excel.

Con Google Sheets se puede crear y formatear hojas de cálculo, agregar fórmulas y funciones, crear gráficos y tablas dinámicas y trabajar con otros usuarios con datos en tiempo real. También admite la importación y exportación de varios formatos de archivos, como CSV y XLSX.

Una de las principales ventajas de Google Sheets es la colaboración en tiempo real. Varias personas pueden trabajar simultáneamente en la misma hoja de trabajo y ver los cambios simultáneamente. Esto facilita el trabajo en proyectos de equipo, aumentando la eficiencia y la productividad.

Para importar el archivo de Excel emisiones_CO2.xlsx hacia Google Sheets, siga estos pasos:

Abra la página de Google Sheets y haga clic en "Ir a Sheets". Inicie sesión en su cuenta de Google si es necesario.
Haga clic en Nueva Hoja de cálculo en blanco.
Cuando haya abierto, haga clic en "Archivo" (File) en el menú superior y luego haga clic en la opción "Importar archivo" (Import).
Haga clic en la pestaña "Subir" (Upload) y seleccione el archivo que desea importar. Puede hacer clic en la opción Examinar para ubicar el archivo en su computadora o arrastrar el archivo dentro de la pestaña.
Espere mientras se carga el archivo. Cuando se complete la carga, verá un mensaje de confirmación y podrá hacer clic en "Importar datos" (Import data).
Después de importar, se mostrarán los datos.
¡Excelente! Los datos se han importado correctamente. En el siguiente video, aprenderá cómo leer estos datos en Google Colab usando el link para compartir de Google Sheets.

https://docs.google.com/spreadsheets/d/1uG3j1h52OzaFXCjGMtNRM1aqTkgTUBmKE2mjzMuJLsk/edit?usp=sharing

In [ ]:
sheet_id = '1uG3j1h52OzaFXCjGMtNRM1aqTkgTUBmKE2mjzMuJLsk'
url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet'

In [ ]:
import pandas as pd
datos_co2_sheets = pd.read_csv(url)

In [ ]:
datos_co2_sheetspd = pd.read_csv(url)

In [ ]:
datos_co2_sheets

,País,ISO 3166-1 alpha-3,Año,Total,Carbón,Aceite,Gas,Cemento,Quema,Otros,Per Capita
0,Afganistán,AFG,1750,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afganistán,AFG,1751,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afganistán,AFG,1752,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afganistán,AFG,1753,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afganistán,AFG,1754,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
63099,Global,WLD,2017,"36,096,739,276","14,506,973,805","12,242,627,935","7,144,928,128","1,507,923,185","391,992,176","302,294,047","4,749,682"
63100,Global,WLD,2018,"36,826,506,600","14,746,830,688","12,266,016,285","7,529,846,784","1,569,218,392","412,115,746","302,478,706","4,792,753"
63101,Global,WLD,2019,"37,082,558,969","14,725,978,025","12,345,653,374","7,647,528,220","1,617,506,786","439,253,991","306,638,573","4,775,633"
63102,Global,WLD,2020,"35,264,085,734","14,174,564,010","11,191,808,551","7,556,290,283","1,637,537,532","407,583,673","296,301,685","4,497,423"
63103,Global,WLD,2021,"37,123,850,352","14,979,598,083","11,837,159,116","7,921,829,472","1,672,592,372","416,525,563","296,145,746","4,693,699"

In [ ]:
sheet_id = '1uG3j1h52OzaFXCjGMtNRM1aqTkgTUBmKE2mjzMuJLsk'
sheet_name = 'emisiones_percapita'
url_percapita = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}'

In [ ]:
percapita_sheets = pd.read_csv(url_percapita)

In [ ]:
percapita_sheets

,País,ISO 3166-1 alpha-3,Año,Total,Carbón,Aceite,Gas,Cemento,Quema,Otros
0,Afganistán,AFG,1750,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afganistán,AFG,1751,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afganistán,AFG,1752,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afganistán,AFG,1753,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afganistán,AFG,1754,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
63099,Global,WLD,2017,"4,749,682","1,908,857","1,610,910","940,144","198,416","51,579","39,776"
63100,Global,WLD,2018,"4,792,753","1,919,213","1,596,350","979,965","204,225","53,634","39,366"
63101,Global,WLD,2019,"4,775,633","1,896,468","1,589,920","984,878","208,309","56,569","39,490"
63102,Global,WLD,2020,"4,497,423","1,807,760","1,427,353","963,695","208,844","51,981","37,789"
63103,Global,WLD,2021,"4,693,699","1,893,923","1,496,614","1,001,585","211,472","52,663","37,443"

In [ ]:
sheet_id = '1uG3j1h52OzaFXCjGMtNRM1aqTkgTUBmKE2mjzMuJLsk'
sheet_name = 'fuentes'
url_fuentes = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}'

In [ ]:
fuentes_sheets = pd.read_csv(url_fuentes)

In [ ]:
fuentes_sheets

,País,ISO 3166-1 alpha-3,Año,Total,Carbón,Aceite,Gas,Cemento,Quema,Otros,Per Capita
0,Afganistán,AFG,1750,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
1,Afganistán,AFG,1751,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
2,Afganistán,AFG,1752,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
3,Afganistán,AFG,1753,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
4,Afganistán,AFG,1754,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
...,...,...,...,...,...,...,...,...,...,...,...
63099,Global,WLD,2017,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."
63100,Global,WLD,2018,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."
63101,Global,WLD,2019,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."
63102,Global,WLD,2020,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."
63103,Global,WLD,2021,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."

In [ ]:
fuentes_sheets.head()

,País,ISO 3166-1 alpha-3,Año,Total,Carbón,Aceite,Gas,Cemento,Quema,Otros,Per Capita
0,Afganistán,AFG,1750,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
1,Afganistán,AFG,1751,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
2,Afganistán,AFG,1752,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
3,Afganistán,AFG,1753,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
4,Afganistán,AFG,1754,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]

Es hora de que pongas a prueba los conocimientos desarrollados durante la clase. Tenemos un link de Google Sheets que contiene datos importantes sobre las emisiones de dióxido de carbono en todo el mundo. El conjunto de datos se obtuvo de Kaggle y consta de las emisiones de CO2 per cápita de todos los países del mundo entre 1990 y 2019.

En este desafío, tu función es leer este link de Google Sheets y luego guardar el DataFrame obtenido en formato CSV. ¿Listo para comenzar?

Iniciemos creando una variable que recibirá el ID de la hoja de trabajo.

¿Y dónde encontramos ese id? En el propio link. Es todo lo que aparece entre d/ y /edit.
Copia el código
sheet_id = '1clj6rGaGlvZaLto2lgfFA7lodefC0OJgC86WgDm1nMU'
Copia el código
A continuación, creamos una variable que almacenará la dirección URL, pero podemos facilitar la escritura usando una f string para el sheet_id. Después de sheet_id tenemos algunos parámetros que se deben agregar.

En este primer momento es importante acceder a la API de visualización de datos de Google. Esto permitirá mostrar los datos de la hoja de cálculo de Google Sheets en Google Colab. Entonces, el parámetro gviz/tq indica que desea acceder a la función de consulta de datos de la API de visualización de datos.

La API también proporciona una forma de recuperar datos de hojas de cálculo como CSV, que es uno de los formatos que puede leer la biblioteca Pandas. Por este motivo indicamos el uso del parámetro tqx=out:csv para que los datos se devuelvan en formato CSV. El parámetro sheet recupera todos los datos de la hoja de trabajo, incluidos los encabezados de las columnas y las filas de datos.

url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet'
Copia el código
Una vez hecho esto, podemos leer los datos pasando la variable url a la función read_csv:

datos = pd.read_csv(url)
Copia el código
Para guardar los datos en formato CSV, basta con utilizar la función to_csv y, entre paréntesis, darle un nombre al archivo agregando el parámetro index=False para que no se agregue una nueva columna de índice:

datos.to_csv('datos_emisiones_co2.csv', index=False)
Copia el código
¡Listo! Pudimos leer datos de Google Sheets con la biblioteca Pandas e incluso guardamos el DataFrame que ahora se puede compartir con otras personas o ser utilizado en análisis posteriores.

### Aula 3 - Leyendo archivos JSON

Importando archivos JSON

In [ ]:
import pandas as pd

In [ ]:
datos_pacientes = pd.read_json('pacientes.json')

In [ ]:
datos_pacientes

,ID_paciente,Enfermedad_corazon,IMC,Fumador,Consumo_alcohol,AVC,Salud_fisica,Salud_mental,Dificultad_caminar,Sexo_biologico,Rango_edad,Raza,Diabetes,Actividad_fisica,Salud_general,Horas_sueño,Asma,Enfermedad_renal,Cancer_piel
0,0,No,16.60,Sí,No,No,3,30,No,Femenino,55-59,Blanca,Sí,Sí,Muy buena,5,Sí,No,Sí
1,1,No,20.34,No,No,Sí,0,0,No,Femenino,80 ó +,Blanca,No,Sí,Muy buena,7,No,No,No
2,2,No,26.58,Sí,No,No,20,30,No,Masculino,65-69,Blanca,Sí,Sí,Razonable,8,Sí,No,No
3,3,No,24.21,No,No,No,0,0,No,Femenino,75-79,Blanca,No,No,Buena,6,No,No,Sí
4,4,No,23.71,No,No,No,28,0,Sí,Femenino,40-44,Blanca,No,Sí,Muy buena,8,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,No,28.29,Sí,No,No,10,20,No,Femenino,65-69,Negra,Sí,Sí,Razonable,8,No,No,No
996,996,No,25.69,Sí,No,No,0,0,No,Femenino,75-79,Blanca,No,Sí,Excelente,8,No,No,No
997,997,Sí,26.99,No,No,No,1,0,No,Masculino,70-74,Blanca,No,Sí,Muy buena,8,No,No,No
998,998,No,44.29,No,No,No,30,0,Sí,Femenino,70-74,Blanca,Sí,No,Buena,6,Sí,No,No
999,999,No,25.83,No,No,No,0,0,No,Masculino,70-74,Negra,Sí,No,Excelente,7,No,No,No

In [ ]:
datos_pacientes_2 = pd.read_json('pacientes_2.json')

In [ ]:
datos_pacientes_2

,Investigación,Año,Pacientes
0,Indicadores clave de enfermedades cardíacas,2020,"{'ID': '01', 'Rango_edad': '55-59', 'Sexo_biol..."
1,Indicadores clave de enfermedades cardíacas,2020,"{'ID': '02', 'Rango_edad': '80 ó +', 'Sexo_bio..."
2,Indicadores clave de enfermedades cardíacas,2020,"{'ID': '03', 'Rango_edad': '65-69', 'Sexo_biol..."

A Gustavo se le asignó la tarea de analizar un archivo JSON que contiene información sobre las ventas de una tienda online.

El archivo "ventas.json" contiene información sobre las ventas realizadas por la tienda en los últimos tres meses. Él necesita cargar esta información en un DataFrame de la biblioteca Pandas para poder analizarla.

¿Qué comando se debe utilizar para leer el archivo JSON "ventas.json" con la biblioteca Pandas?

pd.read_json('ventas.json')

La función read_json permite cargar un archivo JSON directamente en un DataFrame de la biblioteca Pandas.

### Normalizando archivos JSON

In [ ]:
import pandas as pd
df_normalizado = pd.json_normalize(datos_pacientes_2['Pacientes'])

In [ ]:
df_normalizado

,ID,Rango_edad,Sexo_biologico,Raza,IMC,Fumador,Consumo_alcohol,Salud_física,Salud_mental,Dificultad_caminar,Actividad_física,Salud_general,Horas_sueño,Problemas_salud
0,01,55-59,Mujer,Blanca,16.60,Sí,No,3,30,No,Sí,Muy buena,5,"[Diabetes, Asma, Cancer_piel]"
1,02,80 ó +,Mujer,Blanca,20.34,No,No,0,0,No,Sí,Muy buena,7,[AVC]
2,03,65-69,Masculino,Blanca,26.58,Sí,No,20,30,No,Sí,Muy buena,8,"[Diabetes, Asma]"

La normalización de datos es un proceso importante en la ciencia de datos que tiene como objetivo organizar y estandarizar datos para facilitar el análisis y la comparación entre ellos. Cuando se trata de datos en formato JSON (JavaScript Object Notation - Notación de objetos JavaScript), es común que estén anidados, lo que puede dificultar su análisis y manipulación.

La biblioteca Pandas cuenta con una función llamada json_normalize() que permite la transformación de datos a formato tabular, facilitando la visualización y análisis de las informaciones. A continuación, aprenderemos cómo usar esta función para normalizar diferentes tipos de JSON en DataFrames.

Normalizando un JSON simple

A continuación tenemos una variable llamada datos y dentro de ella hay un objeto JSON con tres llaves y sus respectivos valores:

datos = {'Análisis': 'Principales indicadores de enfermedad cardíaca', 'Año': 2020, 'Numero_Pacientes':3}

Para normalizar esta variable, podemos pasarla dentro de la función json_normalize y analizar el DataFrame obtenido:

df = pd.json_normalize(datos)

df

¡El resultado luce genial! Tenemos 3 columnas que son nuestras llaves y una fila que contiene los valores de cada llave.

Normalizando un JSON con múltiples niveles

Hay situaciones en las que el archivo JSON puede contener más de un objeto, como es el caso del siguiente ejemplo, en el que tenemos una lista, almacenada en la variable json_lista, que contiene dos objetos JSON:

json_lista = [
    { 'ID': '01', 'Intervalo_edad': '55-59', 'Sexo_biologico': 'femenino'},
    { 'ID': '02', 'Intervalo_edad': '80 ó +', 'Sexo_biologico': 'femenino'}
]

Para normalizar esta lista podemos aplicar la función json_normalize:

pd.json_normalize(json_lista)

La función json_normalize() es capaz de convertir cada registro de la lista en una línea en forma tabular.

Normalizando un JSON con una lista anidada

Bueno, notamos que la función json_normalize() funciona muy bien en las situaciones anteriores, pero ¿qué pasa en otras situaciones?

Datos como un diccionario

Iniciemos observando la normalización cuando los datos son un diccionario. Tenemos un diccionario almacenado en la variable json_obj. Observe que en la llave “Salud” tenemos otro diccionario:

json_obj = {
    'ID': '01',
    'Intervalo_edad': '55-59',
    'Sexo_biologico': 'Femenino',
    'Salud': {'Dificultad_caminar': 'No',
              'Actividad_fisica': 'Sí',
              'IMC': 16.6,
              'Enfermedad_cardiaca': 'No',
          }
      }
Copia el código
Haciendo la normalización:

pd.json_normalize(json_obj)
Copia el código
index	ID	Intervalo_edad	Sexo_biologico	Salud.Dificultad_caminar	Salud.Actividad_fisica	Salud.IMC	Salud.Enfermedad_cardiaca
0	01	55-59	Femenino	No	Sí	16.6	No
El DataFrame generado tiene una columna para cada información contenida en el diccionario que estaba en “Salud”. Las columnas creadas tienen el prefijo “Salud.”, ya que la información proviene de esa misma llave.

Datos como una lista de diccionarios.

Ahora tenemos una lista de diccionarios almacenados en la variable json_list:

json_list = [
    {
    'ID': '01',
    'Intervalo_edad': '55-59',
    'Sexo_biologico': 'Femenino',
    'Salud': {'Dificultad_caminar': 'No',
              'Actividad_fisica': 'Sí',
              'IMC': 16.6,
              'Enfermedad_cardiaca': 'No',
          }
      },
      {
          'ID': '02',
          'Intervalo_edad': '80 ó +',
          'Sexo_biologico': 'Femenino',
          'Salud': {'Dificultad_caminar': 'No',
                    'Actividad_fisica': 'Sí',
                    'IMC': 20.34,
                    'Enfermedad_cardiaca': 'Sí'}
       }
       ]
Copia el código
Haciendo la normalización:

pd.json_normalize(json_list)
Copia el código
index	ID	Intervalo_edad	Sexo_biologico	Salud.Dificultad_caminar	Salud.Actividad_fisica	Salud.IMC	Salud.Enfermedad_cardiaca
0	01	55-59	Femenino	No	Sí	16.6	No
1	02	80 ó más	Femenino	No	Sí	20.34	Sí
Podemos ver que todos los valores anidados dentro de cada registro de la lista se han convertido en columnas separadas. ¿Qué pasa con los datos que normalizamos en el video anterior? ¿Recuerdas cómo su normalización se hizo de otra manera?

Resumiendo, vamos a copiar los datos del archivo paciente_2.json y vamos a guardarlos en una variable llamada datos_dict.

datos_dict = {
  "Investigación": "Indicadores clave de enfermedades cardíacas",
  "Año": 2020,
  "Pacientes": [
    {
     "ID": "01",
      "Rango_edad": "55-59",
      "Sexo_biologico": "Mujer",
      "Raza": "Blanca",
      "IMC": 16.6,
      "Fumador": "Sí",
      "Consumo_alcohol": "No",
      "Salud_física": 3,
      "Salud_mental": 30,
      "Dificultad_caminar": "No",
      "Actividad_física": "Sí",
      "Salud_general": "Muy buena",
      "Horas_sueño": 5,
      "Problemas_salud": [
        "Diabetes",
        "Asma",
        "Cancer_piel"
      ]
    },
    {
      "ID": "02",
      "Rango_edad": "80 ó +",
      "Sexo_biologico": "Mujer",
      "Raza": "Blanca",
      "IMC": 20.34,
      "Fumador": "No",
      "Consumo_alcohol": "No",
      "Salud_física": 0,
      "Salud_mental": 0,
      "Dificultad_caminar": "No",
      "Actividad_física": "Sí",
      "Salud_general": "Muy buena",
      "Horas_sueño": 7,
      "Problemas_salud": [
        "AVC"
      ]
    },
    {
      "ID": "03",
      "Rango_edad": "65-69",
      "Sexo_biologico": "Masculino",
      "Raza": "Blanca",
      "IMC": 26.58,
      "Fumador": "Sí",
      "Consumo_alcohol": "No",
      "Salud_física": 20,
      "Salud_mental": 30,
      "Dificultad_caminar": "No",
      "Actividad_física": "Sí",
      "Salud_general": "Muy buena",
      "Horas_sueño": 8,
      "Problemas_salud": [
        "Diabetes",
        "Asma"
      ]
    }
  ]
}
Copia el código
Si intentamos normalizar estos datos:

pd.json_normalize(datos_dict)
Copia el código
index	Investigación	Año	Pacientes
0	Indicadores clave de enfermedades cardíacas	2020	{'ID':'01','Rango_edad': '55-59', 'Sexo_b…
Podemos observar que nuestra lista anidada está colocada en una única columna Pacientes. Entonces, usaremos el siguiente código para normalizar los datos, especificando qué columna está anidada:

pd.json_normalize(datos_dict['Pacientes'])
Copia el código
También podemos hacer esto usando el parámetro record_path como ['Pacientes']. Este parámetro se utiliza en la función pd.json_normalize() para especificar la ruta a los registros que deben ser normalizados en un DataFrame separado:

pd.json_normalize(datos_dict, record_path=['Pacientes'])
Copia el código
Con ambos códigos el resultado es el mismo.

index	ID	Rango_edad	Sexo_biologico	Raza	...	Actividad_fisica	Salud_general	Horas_sueño	Problemas_salud
0	01	55-59	Mujer	Blanca	...	Sí	Muy buena	5	Diabetes,Asma,Cancer_piel
1	02	80 ó +	Mujer	Blanca	...	Sí	Muy buena	7	AVC
2	03	65-69	Masculino	Blanca	...	Sí	Muy buena	8	Diabetes,Asma
El resultado parece excelente, pero no incluye las columnas "Investigación" y "Año". Para incluirlas, podemos usar el parámetro meta para especificar otras columnas que queramos en el DataFrame.

pd.json_normalize(
    datos_dict,
    record_path =['Pacientes'],
    meta=[‘Investigación’, 'Año']
)
Copia el código
index	ID	Rango_edad	Sexo_biologico	Raza	...	Actividad_fisica	Salud_general	Horas_sueño	Problemas_salud	Investigación	Año
0	01	55-59	Mujer	Blanca	...	Sí	Muy buena	5	Diabetes,Asma,Cancer_piel	Indicadores clave de enfermedades cardíacas	2020
1	02	80 ó +	Mujer	Blanca	...	Sí	Muy buena	7	AVC	Indicadores clave de enfermedades cardíacas	2020
2	03	65-69	Masculino	Blanca	...	Sí	Muy buena	8	Diabetes,Asma	Indicadores clave de enfermedades cardíacas	2020
¡De esa manera tenemos todas las columnas presentes en el DataFrame!

Importante: En clase nosotros realizamos la normalización en un archivo con formato JSON. Sin embargo, la función json_normalize() sólo acepta un diccionario o una lista de diccionarios. Por esto, en el video se utilizó la estrategia de usar el código: pd.json_normalize(datos_pacientes_2['Pacientes']). Sin embargo, si intentamos utilizar parámetros de la función json_normalize en un archivo JSON, pueden surgir errores. Para solucionar esto, necesitamos importar el módulo json y leer los archivos según el siguiente código:

#Importando la biblioteca Pandas
import pandas as pd

#Importando el módulo JSON
import json

#Leyendo el archivo json usando el módulo Python JSON
with open('pacientes_2.json','r') as f:
    datos = json.loads(f.read())

#Normalizando los datos con los parámetros record_path y meta
pd.json_normalize(datos, record_path='Pacientes', meta=['Investigación', 'Año'])
Copia el código
Y fue así que aprendimos cómo normalizar archivos JSON simples, con múltiples niveles y anidados.

### Escribiendo archivos JSON

In [ ]:
df_normalizado.to_json('historico_pacientes_norm.json')

In [ ]:
pd.read_json('historico_pacientes_norm.json')

,ID,Rango_edad,Sexo_biologico,Raza,IMC,Fumador,Consumo_alcohol,Salud_física,Salud_mental,Dificultad_caminar,Actividad_física,Salud_general,Horas_sueño,Problemas_salud
0,1,55-59,Mujer,Blanca,16.60,Sí,No,3,30,No,Sí,Muy buena,5,"[Diabetes, Asma, Cancer_piel]"
1,2,80 ó +,Mujer,Blanca,20.34,No,No,0,0,No,Sí,Muy buena,7,[AVC]
2,3,65-69,Masculino,Blanca,26.58,Sí,No,20,30,No,Sí,Muy buena,8,"[Diabetes, Asma]"

Para obtener datos en formato JSON podemos utilizar una API (Application Programming Interface). Es una interfaz de programación de aplicaciones que permite la comunicación entre diferentes programas o sistemas.

Hay varios formatos que se pueden utilizar en las API y uno de los más comunes es JSON (JavaScript Object Notation). JSON es un formato ligero para intercambiar información entre sistemas que utiliza la notación basada en objetos de JavaScript.

Tenemos la siguiente situación-problema:

“Una empresa de alimentos saludables tiene problemas con la popularidad de sus productos. A pesar de ofrecer opciones saludables, muchos clientes se muestran reacios a comprar los productos debido a la falta de información sobre los valores nutricionales de las frutas que se utilizan en la producción de alimentos”.

Ante esta situación podemos acceder a una API llamada Fruitvice para recopilar información detallada sobre los valores nutricionales de las frutas que se utilizan en los productos. Con esta información, la empresa podrá actualizar sus empaques y materiales de marketing para resaltar los valores nutricionales de las frutas y así atraer más clientes que buscan opciones saludables. Además, la empresa puede utilizar la información para desarrollar nuevos productos que satisfagan aún más las necesidades nutricionales de su clientela.

Una forma común de acceder a las API es a través de la biblioteca requests. Para eso, también es necesario importar el módulo json:

import requests
import json
Copia el código
Los datos de API Fruitvice se obtendrán con la función request.get('url'). Dentro de ella pasamos la dirección API seguida de api/fruit/all para obtener los datos de todas las frutas.

datos_frutas = requests.get('https://fruityvice.com/api/fruit/all')
Copia el código
Conseguimos recuperar los resultados utilizando la función json.loads(). Para ello es necesario pasar la variable datos_frutas, previamente creada con el atributo text que devuelve el contenido de la respuesta.

resultado = json.loads(datos_frutas.text)
Copia el código
Luego podemos obtener una vista previa del DataFrame.

pd.DataFrame(resultado)
Copia el código
index	genus	name	id	family	order	nutritions
0	Malus	Apple	6	Rosaceae	Rosales	{'carbohydrates': 11.4, 'protein': 0.3, 'fat': 0.4, 'calories': 52, 'sugar': 10.3}
1	Prunus	Apricot	35	Rosaceae	Rosales	{'carbohydrates': 3.9, 'protein': 0.5, 'fat': 0.1, 'calories': 15, 'sugar': 3.2}
2	Persea	Avocado	84	Lauraceae	Laurales	{'carbohydrates': 8.53, 'protein': 2, 'fat': 14.66, 'calories': 160, 'sugar': 0.66}
3	Musa	Banana	1	Musaceae	Zingiberales	{'carbohydrates': 22, 'protein': 1, 'fat': 0.2, 'calories': 96, 'sugar': 17.2}
4	Rubus	Blackberry 64	Rosaceae	Rosales	{'carbohydrates': 9, 'protein': 1.3, 'fat': 0.4, 'calories': 40, 'sugar': 4.5}
5	Fragaria	Blueberry	33	Rosaceae	Rosales	{'carbohydrates': 5.5, 'protein': 0, 'fat': 0.4, 'calories': 29, 'sugar': 5.4}
6	Prunus	Cherry	9	Rosaceae	Rosales	{'carbohydrates': 12, 'protein': 1, 'fat': 0.3, 'calories': 50, 'sugar': 8}
¡Ahora sabemos cómo utilizar la biblioteca requests y el módulo JSON para obtener datos de las API!

Es el momento de poner a prueba tus conocimientos adquiridos durante la clase. El DataFrame que se muestra a continuación se generó después de obtener los datos de la API de Fruitvice:

index	genus	name	id	family	order	nutritions
0	Malus	Apple	6	Rosaceae	Rosales	{'carbohydrates': 11.4, 'protein': 0.3, 'fat': 0.4, 'calories': 52, 'sugar': 10.3}
1	Prunus	Apricot	35	Rosaceae	Rosales	{'carbohydrates': 3.9, 'protein': 0.5, 'fat': 0.1, 'calories': 15, 'sugar': 3.2}
2	Persea	Avocado	84	Lauraceae	Laurales	{'carbohydrates': 8.53, 'protein': 2, 'fat': 14.66, 'calories': 160, 'sugar': 0.66}
3	Musa	Banana	1	Musaceae	Zingiberales	{'carbohydrates': 22, 'protein': 1, 'fat': 0.2, 'calories': 96, 'sugar': 17.2}
4	Rubus	Blackberry 64	Rosaceae	Rosales	{'carbohydrates': 9, 'protein': 1.3, 'fat': 0.4, 'calories': 40, 'sugar': 4.5}
5	Fragaria	Blueberry	33	Rosaceae	Rosales	{'carbohydrates': 5.5, 'protein': 0, 'fat': 0.4, 'calories': 29, 'sugar': 5.4}
6	Prunus	Cherry	9	Rosaceae	Rosales

Este DataFrame tiene 6 columnas: genus (género), name (nombre), id, family (familia), order (orden) e nutritions (nutriciones). Observe que la columna nutritions tiene toda la información nutricional anidada en ella. Por tanto, es necesario normalizar los datos.

El desafío ahora es normalizar este DataFrame.

Opinión del instructor

Recordando que para obtener los datos de la API debemos utilizar los siguientes códigos:

import requests
import json

datos_frutas = requests.get('https://fruityvice.com/api/fruit/all')

resultado = json.loads(datos_frutas)

Copia el código

Para normalizar los datos necesitamos importar la biblioteca Pandas y podemos usar la función json_normalize:

import pandas as pd

datos_frutas_normalizado = pd.json_normalize(resultado)

Copia el código

Comprobemos el DataFrame normalizado:

datos_frutas_normalizado
Copia el código

index	genus	name	...	order	nutritions.carbohydrates	nutritions.protein	nutritions.fat	nutritions.calories	nutritions.sugar
0	Malus	Apple	...	Rosales	11.4	0.3	0.4	52	10.3
1	Prunus	Apricot	...	Rosales	3.9	0.5	0.1	15	3.2
2	Persea	Avocado	...	Laurales	8.53	2.0	14.66	160	0.66
3	Musa	Banana	...	Zingiberales	22.0	1.0	0.2	96	17.2
4	Rubus	Blackberry	...	Rosales	9.0	1.3	0.4	40	4.5
5	Fragaria	Blueberry	...	Rosales	5.5	0.0	0.4	29	5.4
¡Ahora tenemos todas las informaciones separadas!

In [ ]:
import pandas as pd

In [ ]:
datos_html = pd.read_html("Anexo_AFI's 100 años... 100 películas - Wikipedia, la enciclopedia libre.html")

In [ ]:
datos_html

[    Puesto               Título original  \
 0        1                  Citizen Kane
 1        2                    Casablanca
 2        3                 The Godfather
 3        4            Gone with the wind
 4        5            Lawrence of Arabia
 ..     ...                           ...
 95      96                 The Searchers
 96      97              Bringing Up Baby
 97      98                    Unforgiven
 98      99  Guess Who's Coming to Dinner
 99     100           Yankee Doodle Dandy

                                  Título(s) en español  Año de lanzamiento  \
 0     El ciudadano (AR, UY) / Ciudadano Kane (ES, HA)                1941
 1                                          Casablanca                1942
 2                                          El padrino                1972
 3                           Lo que el viento se llevó                1939
 4                                  Lawrence de Arabia                1962
 ..                                                ...                 ...
 95  Más corazón que odio (AR, CL, MX) / Centauros ...                1956
 96  La adorable revoltosa (AR) / La fiera de mi ni...                1938
 97           Sin perdón (ES) / Los imperdonables (HA)                1992
 98  ¿Sabes quién viene a cenar? (AR) / Adivina qui...                1967
 99           Yanqui Dandy (ES) / Triunfo supremo (HA)                1942

                                              Director  \
 0                                        Orson Welles
 1                                      Michael Curtiz
 2                                Francis Ford Coppola
 3   Victor Fleming George Cukor (no acreditado) Sa...
 4                                          David Lean
 ..                                                ...
 95                                          John Ford
 96                                       Howard Hawks
 97                                     Clint Eastwood
 98                                     Stanley Kramer
 99                                     Michael Curtiz

                                               Estudio
 0   RKO Radio Pictures United Artists (1971-1986) ...
 1   Warner Bros.-First National Associated Artists...
 2                                  Paramount Pictures
 3   Metro-Goldwyn-Mayer Turner Entertainment (1986...
 4                                   Columbia Pictures
 ..                                                ...
 95                                       Warner Bros.
 96  RKO Radio Pictures United Artists (1971-1986) ...
 97                                       Warner Bros.
 98                                  Columbia Pictures
 99  Warner Bros.-First National Associated Artists...

 [100 rows x 6 columns],
                         0                                    1
 0  Control de autoridades  Proyectos Wikimedia  Datos: Q719345]

In [ ]:
type(datos_html)

list

In [ ]:
len(datos_html)

2

In [ ]:
top_peliculas = datos_html[0]

In [ ]:
top_peliculas

,Puesto,Título original,Título(s) en español,Año de lanzamiento,Director,Estudio
0,1,Citizen Kane,"El ciudadano (AR, UY) / Ciudadano Kane (ES, HA)",1941,Orson Welles,RKO Radio Pictures United Artists (1971-1986) ...
1,2,Casablanca,Casablanca,1942,Michael Curtiz,Warner Bros.-First National Associated Artists...
2,3,The Godfather,El padrino,1972,Francis Ford Coppola,Paramount Pictures
3,4,Gone with the wind,Lo que el viento se llevó,1939,Victor Fleming George Cukor (no acreditado) Sa...,Metro-Goldwyn-Mayer Turner Entertainment (1986...
4,5,Lawrence of Arabia,Lawrence de Arabia,1962,David Lean,Columbia Pictures
...,...,...,...,...,...,...
95,96,The Searchers,"Más corazón que odio (AR, CL, MX) / Centauros ...",1956,John Ford,Warner Bros.
96,97,Bringing Up Baby,La adorable revoltosa (AR) / La fiera de mi ni...,1938,Howard Hawks,RKO Radio Pictures United Artists (1971-1986) ...
97,98,Unforgiven,Sin perdón (ES) / Los imperdonables (HA),1992,Clint Eastwood,Warner Bros.
98,99,Guess Who's Coming to Dinner,¿Sabes quién viene a cenar? (AR) / Adivina qui...,1967,Stanley Kramer,Columbia Pictures
99,100,Yankee Doodle Dandy,Yanqui Dandy (ES) / Triunfo supremo (HA),1942,Michael Curtiz,Warner Bros.-First National Associated Artists...

HTML (Hypertext Markup Language - Lenguaje de marcación de hipertexto) es el código que utilizamos para estructurar una página web y su contenido. HTML consta de una serie de elementos que se utilizan para delimitar o agrupar diferentes contenidos para que aparezca o actúe de una determinada manera.

Un documento HTML comienza con la etiqueta <html> y termina con la etiqueta </html>. También contiene un encabezado (<head>) que describe el título de la página y otras informaciones relevantes; y un cuerpo (<body>) que contiene el contenido de la página. El encabezado y el cuerpo están delimitados por las etiquetas <head> y </head>, y <body> y </body>, respectivamente.

Dentro del cuerpo podemos utilizar diversos elementos para crear la estructura del contenido. Observe cada detalle en el siguiente ejemplo:

tags <h1> a <h6>: crear títulos y subtítulos.
tags <p>: crear párrafos.
tags <ul> y <li>: crear listas no ordenadas.
tags <img>: insertar imágenes.
tags <table>, <tr>, <th> y <td>: crear tablas.
Además, podemos usar atributos en elementos HTML para especificar propiedades adicionales. Por ejemplo: podemos usar el atributo src en la etiqueta <img> para indicar la dirección de la imagen que queremos mostrar, o el atributo href en la etiqueta <a> para indicar la dirección del link que queremos crear.

Karina está trabajando en un proyecto de análisis de datos y necesita extraer una tabla que está en un archivo HTML. Para ello, decide utilizar la biblioteca Pandas que tiene una función llamada read_html y devuelve una lista de DataFrames de un archivo HTML.

¿Cuál de las siguientes alternativas utiliza correctamente esta función para mostrar la primera tabla contenida en el archivo?

df = pd.read_html('archivo.html')[0]

Aquí obtenemos el primer elemento de la lista que devuelve la función read_html asignado a la variable df que corresponde a la primera tabla encontrada en el archivo HTML.

df = pd.read_html('archivo.html')[1]

De esta forma obtendremos el segundo elemento de la lista, ya que la indexación en Python no comienza en 1.

In [ ]:
top_peliculas.to_html('top_peliculas.html')

In [ ]:
pd.read_html('top_peliculas.html')

[    Unnamed: 0  Puesto              TÃ­tulo original  \
 0            0       1                  Citizen Kane
 1            1       2                    Casablanca
 2            2       3                 The Godfather
 3            3       4            Gone with the wind
 4            4       5            Lawrence of Arabia
 ..         ...     ...                           ...
 95          95      96                 The Searchers
 96          96      97              Bringing Up Baby
 97          97      98                    Unforgiven
 98          98      99  Guess Who's Coming to Dinner
 99          99     100           Yankee Doodle Dandy

                                TÃ­tulo(s) en espaÃ±ol  AÃ±o de lanzamiento  \
 0     El ciudadano (AR, UY) / Ciudadano Kane (ES, HA)                 1941
 1                                          Casablanca                 1942
 2                                          El padrino                 1972
 3                          Lo que el viento se llevÃ³                 1939
 4                                  Lawrence de Arabia                 1962
 ..                                                ...                  ...
 95  MÃ¡s corazÃ³n que odio (AR, CL, MX) / Centauro...                 1956
 96  La adorable revoltosa (AR) / La fiera de mi ni...                 1938
 97          Sin perdÃ³n (ES) / Los imperdonables (HA)                 1992
 98  Â¿Sabes quiÃ©n viene a cenar? (AR) / Adivina q...                 1967
 99           Yanqui Dandy (ES) / Triunfo supremo (HA)                 1942

                                              Director  \
 0                                        Orson Welles
 1                                      Michael Curtiz
 2                                Francis Ford Coppola
 3   Victor Fleming George Cukor (no acreditado) Sa...
 4                                          David Lean
 ..                                                ...
 95                                          John Ford
 96                                       Howard Hawks
 97                                     Clint Eastwood
 98                                     Stanley Kramer
 99                                     Michael Curtiz

                                               Estudio
 0   RKO Radio Pictures United Artists (1971-1986) ...
 1   Warner Bros.-First National Associated Artists...
 2                                  Paramount Pictures
 3   Metro-Goldwyn-Mayer Turner Entertainment (1986...
 4                                   Columbia Pictures
 ..                                                ...
 95                                       Warner Bros.
 96  RKO Radio Pictures United Artists (1971-1986) ...
 97                                       Warner Bros.
 98                                  Columbia Pictures
 99  Warner Bros.-First National Associated Artists...

 [100 rows x 7 columns]]

In [ ]:
top_peliculas.to_html('top_peliculas.html',index=False)

In [ ]:
pd.read_html('top_peliculas.html')

[    Puesto              TÃ­tulo original  \
 0        1                  Citizen Kane
 1        2                    Casablanca
 2        3                 The Godfather
 3        4            Gone with the wind
 4        5            Lawrence of Arabia
 ..     ...                           ...
 95      96                 The Searchers
 96      97              Bringing Up Baby
 97      98                    Unforgiven
 98      99  Guess Who's Coming to Dinner
 99     100           Yankee Doodle Dandy

                                TÃ­tulo(s) en espaÃ±ol  AÃ±o de lanzamiento  \
 0     El ciudadano (AR, UY) / Ciudadano Kane (ES, HA)                 1941
 1                                          Casablanca                 1942
 2                                          El padrino                 1972
 3                          Lo que el viento se llevÃ³                 1939
 4                                  Lawrence de Arabia                 1962
 ..                                                ...                  ...
 95  MÃ¡s corazÃ³n que odio (AR, CL, MX) / Centauro...                 1956
 96  La adorable revoltosa (AR) / La fiera de mi ni...                 1938
 97          Sin perdÃ³n (ES) / Los imperdonables (HA)                 1992
 98  Â¿Sabes quiÃ©n viene a cenar? (AR) / Adivina q...                 1967
 99           Yanqui Dandy (ES) / Triunfo supremo (HA)                 1942

                                              Director  \
 0                                        Orson Welles
 1                                      Michael Curtiz
 2                                Francis Ford Coppola
 3   Victor Fleming George Cukor (no acreditado) Sa...
 4                                          David Lean
 ..                                                ...
 95                                          John Ford
 96                                       Howard Hawks
 97                                     Clint Eastwood
 98                                     Stanley Kramer
 99                                     Michael Curtiz

                                               Estudio
 0   RKO Radio Pictures United Artists (1971-1986) ...
 1   Warner Bros.-First National Associated Artists...
 2                                  Paramount Pictures
 3   Metro-Goldwyn-Mayer Turner Entertainment (1986...
 4                                   Columbia Pictures
 ..                                                ...
 95                                       Warner Bros.
 96  RKO Radio Pictures United Artists (1971-1986) ...
 97                                       Warner Bros.
 98                                  Columbia Pictures
 99  Warner Bros.-First National Associated Artists...

 [100 rows x 6 columns]]

In [ ]:
top_peliculas.to_csv('top_peliculas_1998',index=False)

In [ ]:
datos = pd.read_csv('top_peliculas_1998')
datos.head()

,Puesto,Título original,Título(s) en español,Año de lanzamiento,Director,Estudio
0,1,Citizen Kane,"El ciudadano (AR, UY) / Ciudadano Kane (ES, HA)",1941,Orson Welles,RKO Radio Pictures United Artists (1971-1986) ...
1,2,Casablanca,Casablanca,1942,Michael Curtiz,Warner Bros.-First National Associated Artists...
2,3,The Godfather,El padrino,1972,Francis Ford Coppola,Paramount Pictures
3,4,Gone with the wind,Lo que el viento se llevó,1939,Victor Fleming George Cukor (no acreditado) Sa...,Metro-Goldwyn-Mayer Turner Entertainment (1986...
4,5,Lawrence of Arabia,Lawrence de Arabia,1962,David Lean,Columbia Pictures

XML es un lenguaje de marcación que permite crear y describir datos de forma estructurada y estandarizada. Está compuesto por líneas de comando que utilizan tags (etiquetas) para definir elementos y atributos de los datos.

La estructura básica de un documento XML está formada por:

Una declaración inicial que indica la versión, el encoding y el tipo del documento.
Un elemento raíz que contiene todos los demás elementos del documento.
Elementos secundarios que pueden tener otros elementos o contenido de texto dentro de ellos.
Atributos que proporcionan información adicional sobre los elementos.
Un ejemplo sencillo de un documento XML es:

xml
<?xml version="1.0" encoding="UTF-8"?>
<animales>
  <animal nombre="Mel" tipo="perro" color="marron"/>
  <animal nombre="Vick" tipo="gato" color="blanco"/>
</animales>
Copia el código
En este ejemplo, <animales> es el elemento raíz, <animal> es un elemento secundario con tres atributos (nombre, tipo y color) y Mely Vick son el contenido de texto de los elementos.

Gabriel está analizando datos de una tienda online de productos electrónicos. Recibió un archivo XML que contiene informaciones sobre los productos de la tienda, como: nombre, precio y categoría.

<productos>
  <producto id="1">
    <nombre>Smartphone</nombre>
    <precio>4500.00</precio>
    <categoria>Celulares</categoria>
  </producto>
  <producto id="2">
    <nombre>Notebook</nombre>
    <precio>5000.00</precio>
    <categoria>Computadores</categoria>
  </producto>
  <producto id="3">
    <nombre>Tablet</nombre>
    <precio>2000.00</precio>
    <categoria>Celulares</categoria>
  </producto>
</productos>

Para leer la página, simplemente pase la dirección a la función read_html. Para que se muestre la primera tabla asignamos el primer elemento de la lista, con [0]:

pd.read_html('https://es.wikipedia.org/wiki/Anexo:Pa%C3%ADses_y_territorios_dependientes_por_poblaci%C3%B3n')[0]
Copia el código
¡Y así tendremos la tabla deseada!

###Aula 5 - Leyendo banco de datos

###Creando un banco de datos local

In [ ]:
import sqlalchemy

In [ ]:
from sqlalchemy import create_engine, MetaData, Table, inspect, text

In [ ]:
engine = create_engine('sqlite:///:memory')

Las bases de datos son sistemas que permiten el almacenamiento, organización y recuperación de información de forma estructurada y eficiente. Se utilizan ampliamente en muchas áreas, desde la gestión empresarial hasta la investigación científica. Una base de datos bien diseñada puede mejorar significativamente la eficiencia y precisión de las operaciones de una organización.

Existen bases de datos relacionales y no relacionales. Las bases de datos relacionales representan y almacenan datos en tablas. Las bases de datos no relacionales, también conocidas como bases de datos NoSQL (Not Only SQL - No Sólo SQL), utilizan una variedad de estructuras de datos, como documentos, gráfos o pares llave-valor.

Python ofrece varios paquetes y bibliotecas para trabajar con bases de datos, incluyendo SQLite, MySQL, PostgreSQL, Oracle, MongoDB, entre otros. Uno de los paquetes más comunes utilizados para trabajar con bases de datos relacionales en Python es el paquete sqlite3 que ofrece soporte a bases de datos SQLite. Esta base de datos es liviana e integrada, no requiere un servidor separado para ejecutarse y está instalada de forma nativa en Google Colab.

Para trabajar con esta base de datos, podemos usar SQLAlchemy, una biblioteca de mapeo objeto-relacional (ORM), que permite interactuar con bases de datos relacionales usando código Python. Proporciona una capa de abstracción que permite a los desarrolladores trabajar con objetos Python en lugar de lidiar directamente con las complejidades del lenguaje SQL (Structured Query Language - Lenguaje de consulta estructurado).

Uno de los principales beneficios de utilizar SQLAchemy es la capacidad de crear código más legible y fácil de mantener. Con SQLAlchemy, las operaciones de la base de datos se realizan utilizando métodos en objetos Python, lo que hace que el código sea más claro y menos propenso a errores.

Además, SQLAlchemy ofrece soporte a consultas complejas en bases de datos, lo que permite a los desarrolladores extraer fácilmente información relevante de grandes conjuntos de datos. Esto es especialmente útil en aplicaciones que necesitan manejar grandes cantidades de datos.

Puede encontrar más detalles sobre la biblioteca SQLAchemy en la siguiente documentación.

In [ ]:
import pandas as pd

In [ ]:
archivo = 'clientes_banco.csv'

In [ ]:
datos = pd.read_csv(archivo)

In [ ]:
datos.head()

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
3,5008808,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
4,5008809,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio

In [ ]:
datos.to_sql('clientes',engine,index=False, if_exists='replace')

OperationalError: (sqlite3.OperationalError) database is locked
[SQL:
DROP TABLE clientes]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [ ]:
inspector = inspect(engine)

In [ ]:
print(inspector.get_table_names())

['clientes', 'empleados']

SQL (Structured Query Language - Lenguaje de consulta estructurado) es un lenguaje de consulta utilizado en bases de datos relacionales para insertar, actualizar, consultar y administrar datos.

Para hacer todo esto, existen cláusulas SQL, que son componentes fundamentales de las sentencias SQL, permitiendo especificar detalles sobre cómo se va a realizar la consulta u operación de la base de datos. Las cláusulas se utilizan para filtrar, ordenar, agrupar y limitar los resultados de la consulta.

Las sentencias SQL pueden estar compuestas por una o más cláusulas que proporcionan información adicional sobre lo que se supone que debe hacer la consulta. Las cláusulas más comunes son:

SELECT: especifica qué columnas deben seleccionarse en la consulta.
FROM: Especifica las tablas de la base de datos que se consultarán.
WHERE: Filtra los resultados de la consulta según una o más condiciones especificadas.
ORDER BY: Ordena los resultados de la consulta en orden ascendente o descendente según una o más columnas.
GROUP BY: agrupa los resultados de la consulta basados en una o más columnas.
LIMIT: limita el número de filas devueltas por los resultados de la consulta.
Tenemos un ejemplo sencillo de sintaxis SQL que utiliza el comando SELECT para consultar datos de una tabla de empleados en una base de datos:
SELECT nombre, apellido, salario
FROM empleados
WHERE departamento = 'ventas'
Copia el código
En esta declaración SQL, la cláusula SELECT se utiliza para especificar las columnas que desea consultar de la tabla "empleados", incluyendo "nombre", "apellido" y "salario". La cláusula FROM se utiliza para especificar la tabla que se desea consultar, que en este caso es "empleados".

La cláusula WHERE se utiliza para filtrar los resultados de la consulta según una condición específica. En este ejemplo, la condición es departamento = 'ventas', lo que significa que la consulta solo devolverá empleados que trabajan en el departamento de ventas.

En el próximo vídeo aprenderemos a utilizar algunas de estas cláusulas para realizar las primeras consultas SQL en la tabla que contiene datos de clientes de una institución financiera.

 Discutir en el Foro
 Siguien

### Leyendo una consulta SQL

In [ ]:
query = 'SELECT * FROM clientes WHERE Categoria_de_renta = "Empleado"'

In [ ]:
empleados=pd.read_sql(sql=text(query), con=engine.connect())

In [ ]:
empleados

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1.0,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1.0,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1.0,Casa/Departamento propio
3,5008815,46,Nivel superior,Casado,2,Empleado,Contabilidad,2,270000.0,1.0,Casa/Departamento propio
4,5112956,46,Nivel superior,Casado,2,Empleado,Contabilidad,2,270000.0,1.0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
125396,6034972,59,Nivel intermedio,Divorciado,1,Empleado,Otro,5,99000.0,0.0,Casa/Departamento propio
125397,6034973,59,Nivel intermedio,Divorciado,1,Empleado,Otro,5,99000.0,0.0,Casa/Departamento propio
125398,6034974,59,Nivel intermedio,Divorciado,1,Empleado,Otro,5,99000.0,0.0,Casa/Departamento propio
125399,6034975,59,Nivel intermedio,Divorciado,1,Empleado,Otro,5,99000.0,0.0,Casa/Departamento propio
125400,6034976,59,Nivel intermedio,Divorciado,1,Empleado,Otro,5,99.0,NaN,None

In [ ]:
empleados.to_sql('empleados',con=engine.connect(),index=False)

ValueError: Table 'empleados' already exists.

In [ ]:
empleados.to_sql('empleados',con = engine.connect(), index=False, if_exists='replace')

OperationalError: (sqlite3.OperationalError) database is locked
[SQL:
DROP TABLE empleados]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [ ]:
pd.read_sql_table('empleados',con=engine.connect())

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1.0,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1.0,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1.0,Casa/Departamento propio
3,5008815,46,Nivel superior,Casado,2,Empleado,Contabilidad,2,270000.0,1.0,Casa/Departamento propio
4,5112956,46,Nivel superior,Casado,2,Empleado,Contabilidad,2,270000.0,1.0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
125396,6034972,59,Nivel intermedio,Divorciado,1,Empleado,Otro,5,99000.0,0.0,Casa/Departamento propio
125397,6034973,59,Nivel intermedio,Divorciado,1,Empleado,Otro,5,99000.0,0.0,Casa/Departamento propio
125398,6034974,59,Nivel intermedio,Divorciado,1,Empleado,Otro,5,99000.0,0.0,Casa/Departamento propio
125399,6034975,59,Nivel intermedio,Divorciado,1,Empleado,Otro,5,99000.0,0.0,Casa/Departamento propio
125400,6034976,59,Nivel intermedio,Divorciado,1,Empleado,Otro,5,99.0,NaN,None

In [ ]:
pd.read_sql_table('empleados',con=engine.connect(),columns=['ID_Cliente','Grado_estudio','Rendimiento_anual'])

        ID_Cliente     Grado_estudio  Rendimiento_anual
0          5008804    Nivel superior           427500.0
1          5008805    Nivel superior           427500.0
2          5008806  Nivel intermedio           112500.0
3          5008815    Nivel superior           270000.0
4          5112956    Nivel superior           270000.0
...            ...               ...                ...
125396     6034972  Nivel intermedio            99000.0
125397     6034973  Nivel intermedio            99000.0
125398     6034974  Nivel intermedio            99000.0
125399     6034975  Nivel intermedio            99000.0
125400     6034976  Nivel intermedio               99.0

[125401 rows x 3 columns]

Un equipo de análisis de datos está trabajando para extraer información de una tabla en una base de datos SQL. Decidieron utilizar la biblioteca Pandas para acceder a los datos. Para ello utilizaron las funciones read_sql y read_sql_table.

¿Cuál es la alternativa correcta sobre estas funciones?

La función read_sql_table se utiliza para ejecutar una consulta SQL personalizada en una base de datos.


Alternativa incorreta
La función read_sql se utiliza para cargar datos desde un archivo CSV.


Alternativa incorreta
Ambas funciones devuelven un objeto DataFrame.


¡Eso es! Ambas funciones devuelven un DataFrame.

In [ ]:
query = 'SELECT * FROM clientes'

In [ ]:
pd.read_sql(sql=text(query),con=engine.connect())

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1.0,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1.0,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1.0,Casa/Departamento propio
3,5008808,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0.0,Casa/Departamento propio
4,5008809,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0.0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
244887,6034972,59,Nivel intermedio,Divorciado,1,Empleado,Otro,5,99000.0,0.0,Casa/Departamento propio
244888,6034973,59,Nivel intermedio,Divorciado,1,Empleado,Otro,5,99000.0,0.0,Casa/Departamento propio
244889,6034974,59,Nivel intermedio,Divorciado,1,Empleado,Otro,5,99000.0,0.0,Casa/Departamento propio
244890,6034975,59,Nivel intermedio,Divorciado,1,Empleado,Otro,5,99000.0,0.0,Casa/Departamento propio
244891,6034976,59,Nivel intermedio,Divorciado,1,Empleado,Otro,5,99.0,NaN,None

In [ ]:
#borrando registros

from sqlalchemy.exc import SQLAlchemyError

query= "DELETE FROM clientes WHERE ID_Cliente=5008804"
try:
  r_set = engine.connect().execute(text(query))
except SQLAlchemyError as e:

    print(e)
else:
    print("#Registros borrados", r_set.rowcount)

(sqlite3.OperationalError) database is locked
[SQL: DELETE FROM clientes WHERE ID_Cliente=5008804]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [ ]:
pd.read_sql_table('clientes',con=engine.connect())

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1.0,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1.0,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1.0,Casa/Departamento propio
3,5008808,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0.0,Casa/Departamento propio
4,5008809,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0.0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
244887,6034972,59,Nivel intermedio,Divorciado,1,Empleado,Otro,5,99000.0,0.0,Casa/Departamento propio
244888,6034973,59,Nivel intermedio,Divorciado,1,Empleado,Otro,5,99000.0,0.0,Casa/Departamento propio
244889,6034974,59,Nivel intermedio,Divorciado,1,Empleado,Otro,5,99000.0,0.0,Casa/Departamento propio
244890,6034975,59,Nivel intermedio,Divorciado,1,Empleado,Otro,5,99000.0,0.0,Casa/Departamento propio
244891,6034976,59,Nivel intermedio,Divorciado,1,Empleado,Otro,5,99.0,NaN,None

In [ ]:
#Actualizando registros


query= "UPDATE clientes SET Grado_estudio = 'Nivel superior' WHERE ID_Cliente=5008808"
try:
  r_set = engine.connect().execute(text(query))
except SQLAlchemyError as e:

    print(e)
else:
    print("#Registros actualizados", r_set.rowcount)

(sqlite3.OperationalError) database is locked
[SQL: UPDATE clientes SET Grado_estudio = 'Nivel superior' WHERE ID_Cliente=5008808]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [ ]:
pd.read_sql_table('clientes',con=engine.connect())

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1.0,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1.0,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1.0,Casa/Departamento propio
3,5008808,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0.0,Casa/Departamento propio
4,5008809,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0.0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
244887,6034972,59,Nivel intermedio,Divorciado,1,Empleado,Otro,5,99000.0,0.0,Casa/Departamento propio
244888,6034973,59,Nivel intermedio,Divorciado,1,Empleado,Otro,5,99000.0,0.0,Casa/Departamento propio
244889,6034974,59,Nivel intermedio,Divorciado,1,Empleado,Otro,5,99000.0,0.0,Casa/Departamento propio
244890,6034975,59,Nivel intermedio,Divorciado,1,Empleado,Otro,5,99000.0,0.0,Casa/Departamento propio
244891,6034976,59,Nivel intermedio,Divorciado,1,Empleado,Otro,5,99.0,NaN,None

In [ ]:
inspector = inspect(engine)
print(inspector.get_table_names())

['clientes', 'empleados']

Es el momento de poner a prueba tus conocimientos adquiridos durante la clase.

Usted es responsable de crear una base de datos local de clientes para una institución financiera. Disponemos del archivo CSV con los datos de los clientes.

Tu misión es:

Crear la base de datos local con la biblioteca SQLAlchemy.
Escribir los datos del archivo CSV en esta base de datos local.
Realizar tres actualizaciones en la base de datos:
Actualizar el registro del cliente ID 6840104 cuyo rendimiento anual cambió a 300000.
Eliminar el registro de cliente ID 5008809, ya que esta persona ya no tiene cuenta en la institución financiera.
Crear un nuevo registro de cliente siguiendo las especificaciones a continuación:
ID_cliente: 6850985
Edad: 33
Grado_estudio: Doctorado
Estado_civil: Soltero
Tamaño_familia: 1
Categoria_de_renta: Empleado
Ocupacion: TI
Años_empleado: 2
Rendimiento_anual: 290000
Tiene_carro: 0
Vivienda: Casa/Departamento propio
Consejo importante: Para agregar un nuevo cliente a la tabla, use la cláusula INSERT INTO seguida del nombre de la tabla y luego especifique los nombres de las columnas de la tabla entre paréntesis. Utilice la cláusula VALUES y luego pase entre paréntesis los nuevos valores para este nuevo registro. Asegúrese de que los valores estén en el orden correcto y en el formato adecuado para cada columna.

Para crear la base de datos local es necesario ejecutar los siguientes comandos. Este código consiste en importar la biblioteca sqlalchemy y crear un objeto engine que representa una conexión a una base de datos SQLite en memoria. El método create_engine se utiliza para crear el objeto engine y especificar la base de datos que se utilizará. En este caso, la base de datos es una base de datos SQLite en memoria, que se crea usando sqlite:///:memory::

In [ ]:
import sqlalchemy
from sqlalchemy import create_engine, MetaData, Table, inspect, text
engine = create_engine('sqlite:///:memory:')

A continuación, podemos leer los datos con la función read_csv y escribirlos en el formato de la base de datos con la función to_sql:

In [ ]:
import pandas as pd
archivo = 'clientes_banco.csv'
datos = pd.read_csv(archivo)
datos.to_sql('clientes', engine, index=False)

438463

Después de crear la tabla, podemos obtener un DataFrame con la función read_sql_table:

In [ ]:
pd.read_sql_table('clientes', con=engine.connect())

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
3,5008808,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
4,5008809,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
438458,6840104,62,Nivel intermedio,Divorciado,1,Pensionista,Otro,0,135000.0,0,Casa/Departamento propio
438459,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcción Civil,8,103500.0,0,Casa/Departamento propio
438460,6841878,22,Nivel superior,Soltero,1,Business Partner,Ventas,1,54000.0,0,Vive con los padres
438461,6842765,59,Nivel intermedio,Casado,2,Pensionista,Otro,0,72000.0,0,Casa/Departamento propio
438462,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

¡Ahora vamos a comenzar las actualizaciones de la base de datos!

Actualizar el registro del cliente ID 6840104 cuyo rendimiento anual cambió a 300000:

El siguiente código actualiza el rendimiento anual del ID de cliente 6840104 en la tabla clientes. La variable query contiene una declaración SQL que actualiza ese registro. Luego, la declaración engine.connect() se usa para crear una conexión a la base de datos SQLite. Finalmente, la declaración .execute(text(query)) se utiliza para ejecutar la declaración SQL contenida en la variable query y actualizar el registro en la tabla clientes.

In [ ]:
from sqlalchemy.exc import SQLAlchemyError
query = 'UPDATE clientes SET Rendimiento_anual=300000.0 WHERE ID_Cliente=6840104'
try:
  r_set=engine.connect().execute(text(query))
except SQLAlchemyError as e:
  print(e)
else:
  print("#Registros actualizados: ",r_set.rowcount)

#Registros actualizados:  1

Después de ejecutar este código, puede verificar si la actualización realmente ocurrió leyendo la tabla "clientes"

In [ ]:
pd.read_sql_table('clientes', con=engine.connect())

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
3,5008808,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
4,5008809,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
438458,6840104,62,Nivel intermedio,Divorciado,1,Pensionista,Otro,0,300000.0,0,Casa/Departamento propio
438459,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcción Civil,8,103500.0,0,Casa/Departamento propio
438460,6841878,22,Nivel superior,Soltero,1,Business Partner,Ventas,1,54000.0,0,Vive con los padres
438461,6842765,59,Nivel intermedio,Casado,2,Pensionista,Otro,0,72000.0,0,Casa/Departamento propio
438462,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

Eliminar el registro de cliente ID 5008809, ya que esta persona ya no tiene una cuenta en la institución financiera:

In [ ]:
from sqlalchemy.exc import SQLAlchemyError
query = 'DELETE FROM clientes WHERE ID_Cliente=5008809'
try:
  r_set=engine.connect().execute(text(query))
except SQLAlchemyError as e:
  print(e)
else:
  print("#Registros borrados: ",r_set.rowcount)

#Registros borrados:  1

Cree un nuevo registro de cliente siguiendo las especificaciones dadas anteriormente:

Al trabajar con bases de datos, es común necesitar insertar nuevos registros en nuestras tablas. Para ello podemos utilizar la cláusula INSERT INTO que nos permite añadir nuevos datos de forma práctica y rápida.

Para utilizar esta cláusula, primero debe especificar el nombre de la tabla en la que se insertará el registro. A continuación, debemos pasar entre paréntesis los nombres de las columnas donde se agregarán los nuevos valores. Es importante recordar que el orden de los nombres debe ser el mismo orden en el que se pasarán los valores.

Después de especificar las columnas, usamos la cláusula VALUES para agregar los nuevos valores. Nuevamente debemos pasar entre paréntesis los valores a insertar en el mismo orden en que se especificaron las columnas. Es importante asegurarse de que los valores estén en el formato correcto para cada tipo de datos.

In [ ]:
from sqlalchemy.exc import SQLAlchemyError
query = 'INSERT INTO clientes (ID_Cliente, Edad, Grado_estudio, Estado_civil, ' \
        'Tamaño_familia, Categoria_de_renta, Ocupacion, Años_empleado, ' \
        'Rendimiento_anual, Tiene_carro, Vivienda) ' \
        'VALUES (6850985, 33, "Doctorado", "Soltero", 1, "Empleado", "TI", ' \
        '2, 290000, 0, "Casa/Departamento propio")'

try:
  r_set=engine.connect().execute(text(query))
except SQLAlchemyError as e:
  print(e)
else:
  print("#Registros insertados: ",r_set.rowcount)

#Registros insertados:  1

Para verificar que se realizaron los cambios, puede leer la tabla con el siguiente código:

In [ ]:
pd.read_sql_table('clientes', con=engine.connect())

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
3,5008808,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
4,5008810,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
438458,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcción Civil,8,103500.0,0,Casa/Departamento propio
438459,6841878,22,Nivel superior,Soltero,1,Business Partner,Ventas,1,54000.0,0,Vive con los padres
438460,6842765,59,Nivel intermedio,Casado,2,Pensionista,Otro,0,72000.0,0,Casa/Departamento propio
438461,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio
438462,6850985,33,Doctorado,Soltero,1,Empleado,TI,2,290000.0,0,Casa/Departamento propio